version: '3.8'

services:
  db:
    extends:
      file: ./compose.yml
      service: db
  api:
    extends:
      file: ./compose.yml
      service: api
    image: isaacbatst/turma-fit-api:production
  dashboard:
    extends:
      file: ./compose.yml
      service: dashboard
    image: isaacbatst/turma-fit-dashboard:production
