version: '3.8'

services:
  db:
    extends:
      file: ./compose.production.yml
      service: db
  api:
    extends:
      file: ./compose.production.yml
      service: api
    build: 
      context: ./api
      target: production
  dashboard:
    extends:
      file: ./compose.production.yml
      service: dashboard
    build:
      context: ./dashboard
      target: production
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

