version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 5555:5555
    volumes:
      - ./api/src:/app/src
      - ./api/test:/app/test
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DASHBOARD_URL: ${DASHBOARD_URL}
  dashboard:
    build:
      context: ./dashboard
      target: dev
    depends_on:
      - api
    ports:
      - 3001:3000
    volumes:
      - ./dashboard/src:/app/src
    environment:
      API_URL: ${API_URL}
