export const MUSCLE_REPOSITORY = 'MUSCLE_REPOSITORY';
export const ADMIN_REPOSITORY = 'ADMIN_REPOSITORY';
export const ADMIN_SESSION_REPOSITORY = 'ADMIN_SESSION_REPOSITORY';
export const ID_GENERATOR = 'ID_GENERATOR';
export const ENCRYPTER = 'ENCRYPTER';
export const TOKEN_GENERATOR = 'TOKEN_GENERATOR';
