name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_dashboard:
    name: Push Dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push turma-fit-dashboard
        uses: docker/build-push-action@v5
        with:
          context: ./dashboard
          push: true
          tags: isaacbatst/turma-fit-dashboard:production
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
  push_api:
    name: Push API
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push turma-fit-api
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: isaacbatst/turma-fit-api:production